---
version: '3.5'

networks:
  # Define networks for all images to attach to
  confluent-kafka-net:
    name: confluent-kafka-net

services:
  # Zookeeper: https://hub.docker.com/r/confluentinc/cp-zookeeper/
  zookeeper:
    image: confluentinc/cp-zookeeper:${CONFLUENT_VERSION}
    container_name: zookeeper
    hostname: zookeeper
    networks:
      - confluent-kafka-net
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  # Kafka with SSL:
  kafka:
    image: confluentinc/cp-kafka:${CONFLUENT_VERSION}
    container_name: kafka
    depends_on:
      - zookeeper
    hostname: kafka
    networks:
      - confluent-kafka-net
    ports:
      - "9093:9093"
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_CONFLUENT_SUPPORT_METRICS_ENABLE: 'false'
      KAFKA_CONFLUENT_SUPPORT_CUSTOMER_ID: anonymous
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_NUM_PARTITIONS: 1
      KAFKA_LOG_RETENTION_HOURS: 1
      KAFKA_LOG_CLEANER_ENABLE: 'true'
      KAFKA_CLEANUP_POLICY: delete
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,SSL://kafka:9093
      KAFKA_SSL_KEYSTORE_FILENAME: ${SSL_DIR_KEYSTORE_FILENAME}
      KAFKA_SSL_KEYSTORE_CREDENTIALS: ${SSL_DIR_KEYSTORE_CRED_FILENAME}
      KAFKA_SSL_TRUSTSTORE_FILENAME: ${SSL_DIR_TRUSTSTORE_FILENAME}
      KAFKA_SSL_TRUSTSTORE_CREDENTIALS: ${SSL_DIR_TRUSTSTORE_CRED_FILENAME}
      KAFKA_SSL_KEY_CREDENTIALS: ${SSL_DIR_SSLKEY_CRED_FILENAME}
      KAFKA_SSL_ENABLED_PROTOCOLS: TLSv1.2
      KAFKA_SECURITY_INTER_BROKER_PROTOCOL: SSL
      KAFKA_SSL_CLIENT_AUTH: required
      KAFKA_AUTHORIZER_CLASS_NAME: kafka.security.auth.SimpleAclAuthorizer
      KAFKA_SUPER_USERS: User:${DISTINGUISHED_NAME}
    volumes:
      - ${SSL_DIR}:/etc/kafka/secrets

  # Schema Registry
  schema-registry:
    image: confluentinc/cp-schema-registry:${CONFLUENT_VERSION}
    container_name: schema-registry
    depends_on:
      - zookeeper
      - kafka
    hostname: schema-registry
    networks:
      - confluent-kafka-net
    ports:
      - "8081:8081"
    environment:
      SCHEMA_REGISTRY_AVRO_COMPATIBILITY_LEVEL: full_transitive
      SCHEMA_REGISTRY_HOST_NAME: schema-registry
      SCHEMA_REGISTRY_LISTENERS: http://0.0.0.0:8081

      SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL: zookeeper:2181
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: SSL://kafka:9093
      SCHEMA_REGISTRY_KAFKASTORE_INIT_TIMEOUT_MS: 100000
      SCHEMA_REGISTRY_KAFKASTORE_TOPIC: _schemas
      SCHEMA_REGISTRY_KAFKASTORE_TOPIC_REPLICATION_FACTOR: 1
      SCHEMA_REGISTRY_KAFKASTORE_SSL_KEYSTORE_LOCATION: /etc/kafka/secrets/${SSL_DIR_KEYSTORE_FILENAME}
      SCHEMA_REGISTRY_KAFKASTORE_SSL_KEYSTORE_PASSWORD: ${KEYSTORE_PWD}
      SCHEMA_REGISTRY_KAFKASTORE_SSL_TRUSTSTORE_LOCATION: /etc/kafka/secrets/${SSL_DIR_TRUSTSTORE_FILENAME}
      SCHEMA_REGISTRY_KAFKASTORE_SSL_TRUSTSTORE_PASSWORD: ${TRUSTSTORE_PWD}
      SCHEMA_REGISTRY_KAFKASTORE_SSL_KEY_PASSWORD: ${SSLKEY_PWD}
      SCHEMA_REGISTRY_KAFKASTORE_SSL_ENABLED_PROTOCOLS: TLSv1.2
      SCHEMA_REGISTRY_KAFKASTORE_SECURITY_PROTOCOL: SSL
    volumes:
      - ${SSL_DIR}:/etc/kafka/secrets
